spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/public_db
    username: public_user
    password: publicN3xt!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

